#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/wallpaper/wall.jpg

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           2
bspc config focused_border_color \#abb2bf
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
